---
apiVersion: v1
kind: Pod
metadata:
  name: "my-pod1"
  namespace: default
  labels: 
    app: "my-pod1"
spec:
  containers:
    - name: my-app
      image: "nginx"
      ports:
       - name: my-app
         containerPort: 80
         protocol: TCP
    - name: backend
      image: tomcat
      ports:
       - name: java
         containerPort: 8080
         protocol: TCP
...