---
apiVersion: v1
kind: Namespace
metadata:
  name: ops
...
---
apiVersion: v1
kind: Pod
metadata:  
  namespace: ops
  name: my-app
  labels: 
    app: my-app
spec:
  containers:
    - name: my-app
      image: "nginx"
      ports:
        - name: "nginx"
          containerPort: 80
          protocol: TCP
    - name: backend
      image: tomcat
      ports:
        - name: java
          containerPort: 8080
          protocol: TCP
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: ops
spec:
  type: NodePort
  selector: 
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
...